apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shovel-heroes
  labels:
    app.kubernetes.io/name: shovel-heroes
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shovel-heroes
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
