apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shovel-heroes

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: shovel-heroes
  app.kubernetes.io/managed-by: kubernetes
